// app/components/hero.vue
<template>
  <section class="hero-section">
    <img src="/img/02.png" class="decor02" />
    <img src="/img/03.png" class="decor01" />

    <div class="main-content">
      <img src="/img/01.png" class="nameplate" />
      <div class="button-container">
        <button><img src="/img/0b1.png" class="button" /></button>
        <button><img src="/img/0b2.png" class="button" /></button>
      </div>
    </div>
  </section>
</template>

<style scoped>
.hero-section {
  position: relative;
  width: 100%;
  height: 100vh;
  background-color: var(--lightmode_primary);
  overflow: hidden;
}

.main-content {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 30px;
  z-index: 100;
  padding: 20px;
  width: 100%;
  max-width: 1100px;
}

.nameplate {
  width: 80%;
  max-width: 1053px;
  height: auto;
}

.decor02 {
  position: absolute;
  top: 0;
  left: 0;
  width: min(800px, 35vw);
  z-index: 500;
}

.decor01 {
  position: absolute;
  bottom: 0;
  right: 0;
  width: min(800px, 35vw);
  z-index: 500;
}

.button-container {
  display: flex;
  flex-direction: row;
  gap: 20px;
  flex-wrap: wrap;
  justify-content: center;
}

.button-container button {
  background: none;
  border: none;
  padding: 0;
  cursor: pointer;
  transition:
    transform 0.15s ease,
    filter 0.15s ease;
}

.button-container button:hover {
  transform: scale(1.05);
  filter: brightness(1.1);
}

.button-container button:active {
  transform: scale(0.95);
  filter: brightness(0.9);
}

.button {
  width: clamp(150px, 40vw, 400px);
  height: auto;
  display: block;
}

/* Tablet */
@media (max-width: 768px) {
  .main-content {
    gap: 25px;
  }

  .decor02,
  .decor01 {
    width: 30vw;
  }

  .button-container {
    gap: 15px;
  }
}

/* Mobile */
@media (max-width: 480px) {
  .main-content {
    gap: 20px;
    padding: 15px;
  }

  .decor02,
  .decor01 {
    width: 40vw;
    opacity: 0.5;
  }

  .button-container {
    flex-direction: column;
    gap: 12px;
  }

  .button {
    width: clamp(180px, 60vw, 280px);
  }
}

/* Small mobile */
@media (max-width: 360px) {
  .decor02,
  .decor01 {
    display: none;
  }

  .button {
    width: 70vw;
  }
}
</style>

// app/components/hero.tsx
import React from "react";
import Image from "next/image";

export const Hero = () => {
  return (
    <section className="relative min-h-screen w-full bg-[#e8e4d9] overflow-hidden flex items-center justify-center">
      {/* Top Left Corner Leaf */}
      <div className="absolute top-0 left-0 w-24 h-24 sm:w-32 sm:h-32 md:w-40 md:h-40 lg:w-48 lg:h-48">
        <Image
          src="/02.png"
          alt="Decorative leaf"
          fill
          className="object-contain"
          priority
        />
      </div>

      {/* Bottom Right Corner Leaf */}
      <div className="absolute bottom-0 right-0 w-24 h-24 sm:w-32 sm:h-32 md:w-40 md:h-40 lg:w-48 lg:h-48">
        <Image
          src="/03.png"
          alt="Decorative leaf"
          fill
          className="object-contain"
          priority
        />
      </div>

      {/* Main Content */}
      <div className="flex flex-col items-center justify-center z-10 px-4 sm:px-6 md:px-8">
        {/* Logo/Name */}
        <div className="relative w-[280px] h-[140px] sm:w-[400px] sm:h-[200px] md:w-[500px] md:h-[250px] lg:w-[600px] lg:h-[300px] mb-6 sm:mb-8 md:mb-10">
          <Image
            src="/01.png"
            alt="Faizaan Hoque"
            fill
            className="object-contain"
            priority
          />
        </div>

        {/* Buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-6 md:gap-8">
          {/* View Projects Button */}
          <a
            href="#projects"
            className="relative w-[160px] h-[50px] sm:w-[180px] sm:h-[55px] md:w-[200px] md:h-[60px] cursor-pointer hover:scale-105 active:scale-95 transition-transform duration-150"
          >
            <Image
              src="/0b1.png"
              alt="View Projects"
              fill
              className="object-contain"
            />
          </a>

          {/* Contact Me Button */}
          <a
            href="#contact"
            className="relative w-[160px] h-[50px] sm:w-[180px] sm:h-[55px] md:w-[200px] md:h-[60px] cursor-pointer hover:scale-105 active:scale-95 transition-transform duration-150"
          >
            <Image
              src="/0b2.png"
              alt="Contact Me"
              fill
              className="object-contain"
            />
          </a>
        </div>
      </div>
    </section>
  );
};
