// app/components/projects.vue
<template>
  <div class="projects-section">
    <div class="projects-header">
      <img src="/img/11.png" class="projects-title" />
    </div>

    <div class="projects-grid" v-if="projects">
      <div class="project-card" v-for="project in projects" :key="project.id">
        <div class="card-header">
          <div class="card-icon" :class="project.type">
            <span v-if="project.type === 'hardware'">⬚</span>
            <span v-else>&lt;/&gt;</span>
          </div>
          <div class="card-title-section">
            <h3 class="card-title">{{ project.title }}</h3>
            <span class="card-type" :class="project.type">{{
              project.type
            }}</span>
          </div>
        </div>
        <p class="card-description">{{ project.description }}</p>
        <div class="card-footer">
          <div class="card-tags">
            <span class="tag" v-for="tag in project.tags" :key="tag">{{
              tag
            }}</span>
          </div>
          <a :href="project.github" class="github-link" target="_blank">
            <svg viewBox="0 0 24 24" class="github-icon">
              <path
                d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"
              />
            </svg>
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Project {
  id: number;
  title: string;
  type: "hardware" | "software";
  description: string;
  tags: string[];
  github: string;
}

const { data: projects } = await useFetch<Project[]>("/data/projects.json");
</script>

<style scoped>
.projects-section {
  min-height: 100vh;
  background-color: var(--lightmode_secondary);
  padding: 80px 40px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.projects-header {
  text-align: center;
  margin-bottom: 50px;
}

.projects-title {
  max-width: 600px;
  width: 100%;
  height: auto;
  margin-bottom: 15px;
}

.projects-subtitle {
  font-family: monospace;
  font-size: 1.3rem;
  color: #555;
  letter-spacing: 1px;
}

.projects-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 30px;
  max-width: 1400px;
  width: 100%;
  padding: 0 30px;
}

.project-card {
  background-color: var(--lightmode_primary);
  border: 3px solid #333;
  border-radius: 10px;
  padding: 25px;
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 15px;
}

.card-icon {
  width: 60px;
  height: 60px;
  background-color: #8fa88b;
  border: 2px solid #333;
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: monospace;
  font-size: 1.8rem;
  font-weight: bold;
  color: #333;
}

.card-title-section {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.card-title {
  font-family: monospace;
  font-size: 1.5rem;
  font-weight: bold;
  color: #333;
  margin: 0;
  letter-spacing: 1px;
}

.card-type {
  font-family: monospace;
  font-size: 1rem;
  text-transform: capitalize;
}

.card-type.hardware {
  color: #6b8e6b;
}

.card-type.software {
  color: #8fa88b;
}

.card-description {
  font-family: monospace;
  font-size: 1rem;
  color: #555;
  line-height: 1.5;
  margin: 0;
}

.card-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: auto;
}

.card-tags {
  display: flex;
  gap: 10px;
}

.tag {
  background-color: #8fa88b;
  color: #fff;
  font-family: monospace;
  font-size: 0.9rem;
  padding: 8px 16px;
  border-radius: 5px;
  border: 2px solid #6b8e6b;
}

.github-link {
  display: flex;
  align-items: center;
  justify-content: center;
}

.github-icon {
  width: 34px;
  height: 34px;
  fill: #6b8e6b;
  transition: fill 0.2s ease;
}

.github-link:hover .github-icon {
  fill: #333;
}

/* Large tablet */
@media (max-width: 1200px) {
  .projects-grid {
    grid-template-columns: repeat(2, 1fr);
    max-width: 800px;
    gap: 25px;
  }

  .project-card {
    padding: 20px;
  }
}

/* Tablet */
@media (max-width: 900px) {
  .projects-section {
    padding: 60px 30px;
  }

  .projects-grid {
    grid-template-columns: repeat(2, 1fr);
    max-width: 700px;
    gap: 20px;
    padding: 0 15px;
  }

  .projects-title {
    max-width: 450px;
  }

  .projects-subtitle {
    font-size: 1.1rem;
  }

  .card-icon {
    width: 50px;
    height: 50px;
    font-size: 1.5rem;
  }

  .card-title {
    font-size: 1.3rem;
  }

  .tag {
    padding: 6px 12px;
    font-size: 0.8rem;
  }

  .github-icon {
    width: 28px;
    height: 28px;
  }
}

/* Mobile */
@media (max-width: 600px) {
  .projects-section {
    padding: 50px 20px;
    justify-content: flex-start;
  }

  .projects-header {
    margin-bottom: 30px;
  }

  .projects-grid {
    grid-template-columns: 1fr;
    gap: 18px;
    max-width: 100%;
    padding: 0;
  }

  .projects-title {
    max-width: 280px;
  }

  .projects-subtitle {
    font-size: 0.95rem;
  }

  .project-card {
    padding: 18px;
    gap: 12px;
  }

  .card-icon {
    width: 45px;
    height: 45px;
    font-size: 1.3rem;
  }

  .card-title {
    font-size: 1.15rem;
  }

  .card-type {
    font-size: 0.85rem;
  }

  .card-description {
    font-size: 0.9rem;
  }

  .card-tags {
    gap: 6px;
    flex-wrap: wrap;
  }

  .tag {
    padding: 5px 10px;
    font-size: 0.75rem;
  }

  .github-icon {
    width: 26px;
    height: 26px;
  }
}

/* Small mobile */
@media (max-width: 400px) {
  .projects-section {
    padding: 40px 15px;
  }

  .projects-title {
    max-width: 220px;
  }

  .projects-subtitle {
    font-size: 0.85rem;
  }

  .project-card {
    padding: 15px;
  }

  .card-header {
    gap: 10px;
  }

  .card-icon {
    width: 40px;
    height: 40px;
    font-size: 1.1rem;
  }

  .card-title {
    font-size: 1rem;
  }

  .tag {
    padding: 4px 8px;
    font-size: 0.7rem;
  }
}
</style>

// app/components/projects.tsx
import React from "react";
import Image from "next/image";
import projectsData from "../data/projects.json";

interface Project {
  id: number;
  title: string;
  category: string;
  type: "hardware" | "software";
  description: string;
  tags: string[];
  github: string;
}

const ProjectCard = ({ project }: { project: Project }) => {
  const isHardware = project.type === "hardware";

  return (
    <div className="relative bg-[#e8e4d9] border-[3px] border-[#4a5a4a] p-4 sm:p-5 flex flex-col gap-3 shadow-[6px_6px_0px_0px_#4a5a4a]">
      {/* Header */}
      <div className="flex items-center gap-3">
        {/* Icon */}
        <div className="w-12 h-12 sm:w-14 sm:h-14 bg-[#a8b8a0] border-[3px] border-[#4a5a4a] flex items-center justify-center flex-shrink-0">
          {isHardware ? (
            <svg
              className="w-7 h-7 sm:w-8 sm:h-8 text-[#4a5a4a]"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <rect
                x="4"
                y="4"
                width="16"
                height="16"
                rx="1"
                stroke="currentColor"
                strokeWidth="2"
                fill="none"
              />
              <rect x="8" y="8" width="8" height="8" fill="currentColor" />
              <rect x="2" y="7" width="2" height="2" fill="currentColor" />
              <rect x="2" y="11" width="2" height="2" fill="currentColor" />
              <rect x="2" y="15" width="2" height="2" fill="currentColor" />
              <rect x="20" y="7" width="2" height="2" fill="currentColor" />
              <rect x="20" y="11" width="2" height="2" fill="currentColor" />
              <rect x="20" y="15" width="2" height="2" fill="currentColor" />
              <rect x="7" y="2" width="2" height="2" fill="currentColor" />
              <rect x="11" y="2" width="2" height="2" fill="currentColor" />
              <rect x="15" y="2" width="2" height="2" fill="currentColor" />
              <rect x="7" y="20" width="2" height="2" fill="currentColor" />
              <rect x="11" y="20" width="2" height="2" fill="currentColor" />
              <rect x="15" y="20" width="2" height="2" fill="currentColor" />
            </svg>
          ) : (
            <svg
              className="w-7 h-7 sm:w-8 sm:h-8 text-[#4a5a4a]"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <rect
                x="3"
                y="5"
                width="18"
                height="14"
                rx="1"
                stroke="currentColor"
                strokeWidth="2"
                fill="none"
              />
              <path
                d="M7 9l3 3-3 3"
                stroke="currentColor"
                strokeWidth="2"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M12 15h5"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
          )}
        </div>

        {/* Title and Category */}
        <div className="flex flex-col">
          <h3 className="text-lg sm:text-xl font-bold text-[#4a5a4a] tracking-wide">
            {project.title}
          </h3>
          <span className="text-sm sm:text-base text-[#6b8a6b] italic">
            {project.category}
          </span>
        </div>
      </div>

      {/* Description */}
      <p className="text-sm sm:text-base text-[#4a5a4a] leading-relaxed">
        {project.description}
      </p>

      {/* Tags and GitHub */}
      <div className="flex items-center justify-between mt-auto">
        <div className="flex flex-wrap gap-2">
          {project.tags.map((tag, index) => (
            <span
              key={index}
              className="px-3 py-1 text-xs sm:text-sm bg-[#6b8a6b] text-white font-medium border-2 border-[#4a5a4a] shadow-[2px_2px_0px_0px_#4a5a4a]"
            >
              {tag}
            </span>
          ))}
        </div>

        <a
          href={project.github}
          target="_blank"
          rel="noopener noreferrer"
          className="flex-shrink-0 ml-2 hover:scale-110 active:scale-95 transition-transform duration-150"
        >
          <svg
            className="w-8 h-8 sm:w-9 sm:h-9 text-[#6b8a6b]"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
          </svg>
        </a>
      </div>
    </div>
  );
};

const Projects = () => {
  const projects: Project[] = projectsData.projects as Project[];

  return (
    <section
      id="projects"
      className="w-full bg-[var(--lightmode-secondary)] py-12 sm:py-16 md:py-20 px-4 sm:px-6 md:px-8"
    >
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex justify-center mb-8 sm:mb-12">
          <div className="relative w-[280px] h-[80px] sm:w-[400px] sm:h-[110px] md:w-[500px] md:h-[140px] lg:w-[600px] lg:h-[160px]">
            <Image
              src="/11.png"
              alt="My Projects - A collection of hardware and software creations"
              fill
              className="object-contain"
            />
          </div>
        </div>

        {/* Projects Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 md:gap-8">
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;
